INSERT OVERWRITE DIRECTORY '/PDA/hive/hiveq1' ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' SELECT stateName, COUNT(id) FROM cars GROUP BY stateName ORDER BY stateName;

INSERT OVERWRITE DIRECTORY '/PDA/hive/hiveq2' ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' SELECT manufacturer, COUNT(id) FROM cars GROUP BY manufacturer ORDER BY manufacturer;

INSERT OVERWRITE DIRECTORY '/PDA/hive/hiveq3' ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' SELECT price, cylinders FROM cars WHERE price < 50000 AND cylinders != 'others';
